service: aws-nodejs-typescript-cloudwatch-log-example

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: [aws-region]


functions:
  processor:
    handler: handler.processor
    reservedConcurrency: 5 # default, change according to your needs
    layers: # AWS Powertools layer for EMF metrics
      - arn:aws:lambda:eu-west-1:094274105915:layer:AWSLambdaPowertoolsTypeScript:7
    events:
      - cloudwatchLog: ${self:custom.logGroup}

# custom variables
custom:
  logGroup: <logGroup-arn> # set your logGroup arn here
  stages:
    - dev
    - test
    - acc
    - prod


