service: aws-nodejs-typescript-cloudwatch-log-example

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: [aws-region]


functions:
  processor:
    handler: handler.processor
    events:
      - cloudwatchLog: ${self:custom.logGroup}

# custom variables
custom:
  logGroup: <logGroup-arn> # set your logGroup arn here
  stages:
    - dev
    - test
    - acc
    - prod


