service: aws-nodejs-typescript-dynamodb-streams-example

plugins:
  - serverless-webpack
  - serverless-stage-manager
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: [aws-region]

functions:
  receiver:
    handler: handler.processor
    reservedConcurrency: 5 # default, change according to your needs
    layers: # AWS Powertools layer for EMF metrics
      - arn:aws:lambda:eu-west-1:094274105915:layer:AWSLambdaPowertoolsTypeScript:7
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.stream_arn}

custom:
  stream_arn: <your-dynamodb-stream-arn>
  stages:
    - dev
    - test
    - acc
    - prod
  prune:
    automatic: true
    number: 3
